 <ul class="nav nav-tabs" id="nav" style="font-size:15px;">
                <li><a href="#">Sistema</a>
                <ul>
                    <li><a href="<?php echo $this->url(array('controller'=>'aluno','action'=>'matricula')); ?>">Matricular Aluno</a></li>
                    <li><a href="#">Requisi&ccedil;&atilde;o de Documentos</a></li>
                </ul>
                </li>
                <li><a href="#">Relat&oacute;rios</a>
                <ul>
                    <li><a href="#">Faltas</a></li>
                    <li><a href="#">Desempenho escolar</a></li>
                    <li><a href="#">Informa&ccedil;&otilde;es de Aluno</a></li>
                </ul>
                </li>
                <li><a href="#">Pesquisa de Vagas</a></li>
        		<li class="clearfix"></li>
    </ul>
	
