<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
    </head>
    <body>
        <h1>Solicita&ccedil;&atilde;o de Nova Senha</h1>
        <p>
            Uma nova senha do sistema foi solicitada.
            Se n&atilde;o foi voc&ecirc; quem solicitou isso ignore essa
            mensagem e reporte imediatamente ao suporte.
            Para acessar sua nova senha acesse o link abaixo:
        </p>
    </body>
</html>
